ushahidi/SMSSync

- contributors.json
> - Updated contributors

- .travis.yml
- build.gradle
- dependencies/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- smssync/build.gradle
- smssync/src/main/AndroidManifest.xml
- smssync/src/main/java/org/addhen/smssync/data/twitter/AuthHeaders.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/AuthToken.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/OAuthResponse.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/PersistedSessionManager.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/RequestUtils.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/SerializationStrategy.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/Session.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/SessionManager.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/TweetRequest.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/Twitter.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/TwitterAuthConfig.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/TwitterAuthToken.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/TwitterBuilder.java
- smssync/src/main/java/org/addhen/smssync/data/twitter/TwitterSession.java
- smssync/src/main/java/org/addhen/smssync/presentation/App.java
- smssync/src/main/java/org/addhen/smssync/presentation/ui/activity/MainActivity.java
- smssync/src/main/java/org/addhen/smssync/presentation/ui/activity/OauthActivity.java
- smssync/src/main/java/org/addhen/smssync/presentation/ui/fragment/IntegrationFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/ui/fragment/TwitterProfileFragment.java
- smssync/src/main/java/org/addhen/smssync/smslib/sms/ProcessSms.java
- smssync/src/main/res/layout/fragment_twitter_profile.xml
- smssync/src/main/res/layout/twitter_auth_login.xml
- smssync/src/main/res/values/strings.xml
- Implement Twitter authlogin flow and session management.
- Show logged user's twitter profile.
- Add twitter request string for volley http based client.
> 262 bug fix

- dependencies/dependencies.gradle
- smssync/build.gradle
- smssync/src/main/AndroidManifest.xml
- smssync/src/main/java/org/addhen/smssync/data/twitter/Twitter.java
- smssync/src/main/java/org/addhen/smssync/presentation/App.java
- smssync/src/main/java/org/addhen/smssync/presentation/di/component/AppActivityComponent.java
- smssync/src/main/java/org/addhen/smssync/presentation/di/component/FilterComponent.java
- smssync/src/main/java/org/addhen/smssync/presentation/di/component/LogComponent.java
- smssync/src/main/java/org/addhen/smssync/presentation/di/component/MessageComponent.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/activity/AppCompatPreferenceActivity.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/activity/MainActivity.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/activity/OauthActivity.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/activity/SettingsActivity.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/adapter/FilterAdapter.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/adapter/LogAdapter.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/adapter/MessageAdapter.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/FilterFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/IntegrationFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/LogFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/MessageFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/SettingFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/TwitterProfileFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/listener/OnSwipeableRecyclerViewTouchListener.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/navigation/Launcher.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/widget/KeywordView.java
- smssync/src/main/res/values/attrs.xml
- smssync/src/main/res/values/dimens.xml
- Make a widget for showing keywords
- Use nineolddroid to provide animations on pre honeycomb devices
- Make the widget configurable via xml
- Supports icons and animations
- Provide twitter keys via build scripts
> Fix #295 - Implement custom widget for displaying keywords

- .travis.yml
- dependencies/dependencies.gradle
- smssync/src/main/AndroidManifest.xml
- smssync/src/main/java/org/addhen/smssync/data/entity/SyncScheme.java
- smssync/src/main/java/org/addhen/smssync/data/net/AppHttpClient.java
- smssync/src/main/java/org/addhen/smssync/domain/entity/HttpNameValuePair.java
- smssync/src/main/java/org/addhen/smssync/domain/entity/SyncSchemeEntity.java
- smssync/src/main/java/org/addhen/smssync/domain/util/DataFormatUtil.java
- smssync/src/main/java/org/addhen/smssync/presentation/model/SyncSchemeModel.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/activity/MainActivity.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/adapter/MessageAdapter.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/MessageFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/PublishedMessageFragment.java
- smssync/src/main/res/menu/menu_messages.xml
- smssync/src/main/res/values/strings.xml
- smssync/src/main/res/xml/message_searchable.xml
- Get search form on toolbar to work.
- Implement Filterable on message adapter for basic filtering
by message body
- Upgraded to use the latest version Raiburari
- Bump android compile and target version to 23
- Replace removed http related classes in Android M with custom ones
Android Marshmallow removed a lot of deprecated HTTP classes. Making
compiling with v23 fail.
> Fix #317 - Implement message search

- build.gradle
- smssync/build.gradle
- smssync/src/main/java/org/addhen/smssync/presentation/util/TimeFrequencyUtil.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/AutomationSettingsFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/widget/TimePreference.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/widget/TimePreferenceFragmentDialog.java
- Add okay button to save the selected frequency
- Remove debug log messages
- Call dismiss on dialog to make sure it's dismissed when okayed
- Also made the default frequency five minutes instead of 5 hours
> Fix #339 - Fix a bug where selected time frequency is not saved

- website-src/layouts/partials/menu.html
- website-src/static/css/hugo-bootswatch.css
- website-src/static/sass/hugo-bootswatch.scss
Hide forkme badge when on mobile
Move inline style declaration for fork me badge
to the css style then hide the badge when on a
mobile device
> Fix #340 Forkme Badge on Mobile

- smssync/src/main/java/org/addhen/smssync/data/message/TweetMessage.java
This variable doesn't seem to be used
> Remove unused variable

- smssync/src/main/java/org/addhen/smssync/data/message/TweetMessage.java
> Bugfix: only forward each pending tweet once

- smssync/src/main/java/org/addhen/smssync/data/message/PostMessage.java
> Prevent pending PostMessages from synching multiple times

- smssync/proguard-project.pro
> Update proguard rules to workaround samsung compat support

- smssync/src/main/java/org/addhen/smssync/presentation/service/SmsReceiverService.java
> Check messages is not null before fetching first item

- smssync/src/main/java/org/addhen/smssync/presentation/service/SmsReceiverService.java
> Create statusIntent at point of use

- smssync/src/main/java/org/addhen/smssync/presentation/service/SmsReceiverService.java
> Remove unused properties from SmsReceiverService

- smssync/src/main/java/org/addhen/smssync/presentation/service/SmsReceiverService.java
> Scope the `sms` reference more finely in SmsReceiverService

- smssync/src/main/java/org/addhen/smssync/presentation/util/Utility.java
- smssync/src/test/java/org/addhen/smssync/presentation/util/UtilityTest.java
> Make string capitalisation safe

- smssync/src/main/java/org/addhen/smssync/data/message/PostMessage.java
- smssync/src/main/java/org/addhen/smssync/data/message/TweetMessage.java
- smssync/src/main/java/org/addhen/smssync/presentation/service/AutoSyncScheduledService.java
> Remove option to pass UUID to syncPendingMessages() methods

- .travis.yml
- dependencies/dependencies.gradle
Fixes # 
This `PR` makes the following changes:
- Upgrades Raiburari
- Upgrade build tools
- Clear cache on Travis
- Disable container-based infrastructure on Travis because it was breaking builds
> 447 upgrade raiburari

- smssync/src/main/java/org/addhen/smssync/presentation/receiver/ConnectivityChangedReceiver.java
Fixes #420 
This `PR` makes the following changes:
- Add checks for when there's data connectivity or not and log appropriate message.
> Log messages for gained and lost data connectivity

- smssync/src/main/java/org/addhen/smssync/data/message/PostMessage.java
- smssync/src/test/java/org/addhen/smssync/data/message/PostMessageTest.java
Fixes for #414
This `PR` makes the following changes:
- Add filter status checks before processing messages
- Add test for the implementation
@alxndrsn  If you get the chance, mind reviewing this? I was confusing myself on this one and would appreciate a second eye.
> 414 whitelist causes dup sync

- dependencies/dependencies.gradle
- smssync/build.gradle
- smssync/src/main/AndroidManifest.xml
- smssync/src/main/java/org/addhen/smssync/data/message/ProcessMessageResult.java
- smssync/src/main/java/org/addhen/smssync/data/net/AppHttpClient.java
- smssync/src/main/java/org/addhen/smssync/data/net/BaseHttpClient.java
- smssync/src/main/java/org/addhen/smssync/data/net/MessageHttpClient.java
- smssync/src/main/java/org/addhen/smssync/data/util/Logger.java
- smssync/src/main/java/org/addhen/smssync/presentation/App.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/activity/QrcodeReaderActivity.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/adapter/MessageAdapter.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/AddKeywordFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/AddPhoneNumberFilterFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/AddWebServiceFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/AutomationSettingsFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/FilterFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/LogFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/MessageFragment.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/PublishedMessageFragment.java
- smssync/src/main/res/values/strings.xml
This `PR` makes the following changes:
- Fixes crashes due to code changes
- Fix checkbox flipping animation.
> Fix checkbox flipping animation

- smssync/src/internal/java/org/addhen/smssync/data/repository/InternalMessageDataRepository.java
- smssync/src/main/java/org/addhen/smssync/data/net/MessageHttpClient.java
- smssync/src/main/java/org/addhen/smssync/data/repository/MessageDataRepository.java
- smssync/src/main/java/org/addhen/smssync/domain/repository/MessageRepository.java
- smssync/src/main/java/org/addhen/smssync/domain/usecase/message/PublishAllMessagesUsecase.java
- smssync/src/main/java/org/addhen/smssync/presentation/di/component/AppServiceComponent.java
- smssync/src/main/java/org/addhen/smssync/presentation/di/component/MessageComponent.java
- smssync/src/main/java/org/addhen/smssync/presentation/di/module/MessageModule.java
- smssync/src/main/java/org/addhen/smssync/presentation/presenter/message/PublishAllMessagesPresenter.java
- smssync/src/main/java/org/addhen/smssync/presentation/presenter/message/PublishMessagePresenter.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/message/PublishAllMessagesView.java
- smssync/src/main/java/org/addhen/smssync/presentation/view/ui/fragment/MessageFragment.java
- smssync/src/main/java/org/addhen/smssync/smslib/sms/ProcessSms.java
Pull pending messages from the db directly then sync them
instead of getting them passed via the UI.
> Fix issue with imported message getting synced multiple times

- smssync/src/main/java/org/addhen/smssync/data/twitter/TwitterOAuthView.java
In compliance with Google Play warnings about inherent security
vulnerability.
> Removed onReceivedSslError override
